# Generated by Django 5.1 on 2024-08-23 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('trainee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('gender', models.CharField(max_length=10, null=True)),
                ('birth_data', models.DateField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('trackobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.track')),
            ],
        ),
    ]
